### ISSUE TITLE
Not building with Ubuntu Studio LTS or 23.10

### ISSUE THREAD

**Issue by rominator1983** [moddevices/mod-host#70]
I get the following error when trying to build the latest master. Probably has something to do with the latest changes since it has been working 2 weeks ago.
Pretty vanilla Ubuntu Studio except for installing needed jack development libraries etc.

I checked and jack_set_property and jack_get_property are present in /usr/include/jack/metadata.h

```
cc ./src/completer.o ./src/effects.o ./src/filter.o ./src/lv2_evbuf.o ./src/mod-host.o ./src/monitor.o ./src/protocol.o ./src/socket.o ./src/state-paths.o ./src/symap.o ./src/uridmap.o ./src/utils.o ./src/worker.o ./src/dsp/compressor_core.o ./src/monitor/monitor-client.o ./src/sha1/sha1.o ./src/rtmempool/rtmempool.o -s -Wl,--no-undefined -ljackserver -llilv-0 -ldl -lsratom-0 -lsord-0 -lserd-0 -lpthread -lm  -lfftw3_threads -lfftw3f_threads -lfftw3 -lfftw3f -lreadline -lrt -shared -o mod-host.so
/usr/bin/ld: ./src/effects.o: in function `effects_add':
effects.c:(.text+0xa983): undefined reference to `jack_set_property'
/usr/bin/ld: effects.c:(.text+0xa9da): undefined reference to `jack_set_property'
/usr/bin/ld: ./src/effects.o: in function `effects_cv_map':
effects.c:(.text+0xe8a1): undefined reference to `jack_get_property'
/usr/bin/ld: effects.c:(.text+0xe9eb): undefined reference to `jack_get_property'
collect2: error: ld returned 1 exit status
make: *** [Makefile:125: mod-host.so] Error 1

```

**Comment by rominator1983** [comment]
I could try and step back the last cmmits to see where it works but I suppose you might already know where the problem is since you did some linker command changes recently. @falkTX

**Comment by falkTX** [comment]
I know what causes this, the functions were missing from libjackserver side by mistake.
Fixed in https://github.com/jackaudio/jack2/commit/171ec33b58d3e51ab90cd7432f07aba0c351f1e2 but it will be a while before it spreads out to distros (and still needs a release first anyway)

I guess on this change in particular we need to only do it when building for mod-app, since that is where it is crucial

**Comment by rominator1983** [comment]
Can this be detected at build time for pragmas or something?

**Comment by rominator1983** [comment]
this got introduced with https://github.com/moddevices/mod-host/commit/160907041cd8c14d35c2d0c49a2639d95574baba

**Comment by falkTX** [comment]
Fixed in dca85d7f7c1c454e45db44e8f2df2e137ccb9425
